// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 16.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Mobioos.Generators.AspNetCore
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Common.Generator.Framework.Extensions;
    using Mobioos.Generators.AspNetCore;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ApiController : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 2 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"

    var model = (ApiInfo)Model;
    var actions = ((ApiInfo)Model).Actions;
    var viewModelsNamespace = $"{ApplicationId}.Backend.ViewModels";
    var controllerName = $"{ApplicationId}{model.Id}";

            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Net;\r\nusing System.Linq;\r\nusing System.Threading.Task" +
                    "s;\r\nusing System.Collections.Generic;\r\nusing Microsoft.AspNetCore.Authorization;" +
                    "\r\nusing Microsoft.AspNetCore.Mvc;\r\nusing Microsoft.EntityFrameworkCore;\r\nusing ");
            
            #line 16 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write(".Backend.DataModels;\r\nusing ");
            
            #line 17 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write(".Backend.Models;\r\nusing ");
            
            #line 18 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write(".Backend.Services;\r\nusing ");
            
            #line 19 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewModelsNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 21 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write(".Backend.Api\r\n{\r\n    /// <summary>\r\n    /// Controller responsible for all data i" +
                    "nteractions with the ");
            
            #line 24 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\r\n    /// </summary>\r\n    public partial class ");
            
            #line 26 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(controllerName));
            
            #line default
            #line hidden
            this.Write("Controller : Controller\r\n    {\r\n");
            
            #line 28 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"

    foreach (var entity in Entities)
    {

            
            #line default
            #line hidden
            this.Write("        private I");
            
            #line 32 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("Service _");
            
            #line 32 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Service;\r\n");
            
            #line 33 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"

    }

    var lastEntity = Entities.LastOrDefault();

            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// Initialize a new instance of\r\n        /// <s" +
                    "ee cref = \"");
            
            #line 41 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write(".Backend.Api.");
            
            #line 41 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(controllerName));
            
            #line default
            #line hidden
            this.Write("Controller\"/> class.\r\n        /// </summary>\r\n        public ");
            
            #line 43 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(controllerName));
            
            #line default
            #line hidden
            this.Write("Controller(");
            
            #line 43 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Entities.Count > 0 ? "" : ")"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 44 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"

    foreach (var entity in Entities)
    {

            
            #line default
            #line hidden
            this.Write("            I");
            
            #line 48 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("Service ");
            
            #line 48 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Service");
            
            #line 48 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(!entity.Equals(lastEntity) ? "," : ")"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 49 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"

    }

            
            #line default
            #line hidden
            this.Write("        {\r\n");
            
            #line 53 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"

    foreach (var entity in Entities)
    {

            
            #line default
            #line hidden
            this.Write("             _");
            
            #line 57 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Service = ");
            
            #line 57 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Service;\r\n");
            
            #line 58 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"

    }

            
            #line default
            #line hidden
            this.Write("        }\r\n");
            
            #line 62 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"

    foreach (var action in actions)
    {
        var firstParameter = action
            .Parameters
            .FirstOrDefault();

        var lastParameter = action.Parameters.LastOrDefault();

            
            #line default
            #line hidden
            this.Write("\r\n\r\n        [");
            
            #line 73 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.CSharpType()));
            
            #line default
            #line hidden
            this.Write("]\r\n        [Route(\"");
            
            #line 74 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Url));
            
            #line default
            #line hidden
            this.Write("\")]\r\n");
            
            #line 75 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"

        if (action.ReturnType != null)
        {
            var returnType = $"{viewModelsNamespace}.{action.ReturnType.Id}";

            
            #line default
            #line hidden
            this.Write("        [ProducesResponseType(\r\n            typeof(");
            
            #line 81 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(returnType));
            
            #line default
            #line hidden
            this.Write("),\r\n            200)]\r\n");
            
            #line 83 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"

        }

            
            #line default
            #line hidden
            this.Write("        public async Task<IActionResult> ");
            
            #line 86 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Id));
            
            #line default
            #line hidden
            this.Write("(\r\n");
            
            #line 87 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"

        foreach (var parameter in action.Parameters)
        {
            var parameterType = parameter.CSharpType();

            if (parameter.IsModel())
            {
                parameterType =
                    $"{viewModelsNamespace}.{parameterType.ToPascalCase()}";
            }

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 98 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 98 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Id));
            
            #line default
            #line hidden
            
            #line 98 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(!parameter.Equals(lastParameter) ? "," : ")"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 99 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Api\Templates\ApiController.tt"

        }

        if (action.Type?.ToLower() == "datacreate"
           && firstParameter != null)
        {
            var template = new ApiPostTemplate(action);
            Write(template.TransformText());
        }
        else if (action.Type?.ToLower() == "dataupdate"
                && firstParameter != null)
        {
            var template = new ApiPutTemplate(action);
            Write(template.TransformText());
        }
        else if (action.Type == "datadelete"
                && firstParameter != null)
        {
            var template = new ApiDeleteTemplate(action);
            Write(template.TransformText());
        }
        else if (action.Type?.ToLower() == "datalist")
        {
            var template = new ApiGetAllTemplate(
                action,
                ApplicationId);

            Write(template.TransformText());
        }
        else if (action.Type?.ToLower() == "dataget")
        {
            var template = new ApiGetTemplate(
                action,
                ApplicationId);

            Write(template.TransformText());
        }
    }

            
            #line default
            #line hidden
            this.Write("\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
