// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 15.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Mobioos.Generators.AspNetCore
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using Mobioos.Scaffold.TextTemplating;
    using Mobioos.Generators.AspNetCore;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\DEV\Generators\Mobioos\Common\Templates\Views\Account\Register.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class Register : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 1 "D:\DEV\Generators\Mobioos\Common\Templates\Views\Account\Register.tt"
 var model = (SmartAppInfo)Model; 
            
            #line default
            #line hidden
            this.Write("@model ");
            
            #line 2 "D:\DEV\Generators\Mobioos\Common\Templates\Views\Account\Register.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(".Backend.Models.RegisterViewModel\r\n@{\r\n    ViewData[\"Title\"] = \"Register\";\r\n}\r\n\r\n" +
                    "<h2>@ViewData[\"Title\"].</h2>\r\n\r\n<form asp-controller=\"Account\" asp-action=\"Regis" +
                    "ter\" asp-route-returnurl=\"@ViewData[\"ReturnUrl\"]\" method=\"post\" class=\"form-hori" +
                    "zontal\">\r\n    <h4>Create a new account.</h4>\r\n    <hr />\r\n    <div asp-validatio" +
                    "n-summary=\"All\" class=\"text-danger\"></div>\r\n    <div class=\"form-group\">\r\n      " +
                    "  <label asp-for=\"Email\" class=\"col-md-2 control-label\"></label>\r\n        <div c" +
                    "lass=\"col-md-10\">\r\n            <input asp-for=\"Email\" class=\"form-control\" />\r\n " +
                    "           <span asp-validation-for=\"Email\" class=\"text-danger\"></span>\r\n       " +
                    " </div>\r\n    </div>\r\n    <div class=\"form-group\">\r\n        <label asp-for=\"Passw" +
                    "ord\" class=\"col-md-2 control-label\"></label>\r\n        <div class=\"col-md-10\">\r\n " +
                    "           <input asp-for=\"Password\" class=\"form-control\" />\r\n            <span " +
                    "asp-validation-for=\"Password\" class=\"text-danger\"></span>\r\n        </div>\r\n    <" +
                    "/div>\r\n    <div class=\"form-group\">\r\n        <label asp-for=\"ConfirmPassword\" cl" +
                    "ass=\"col-md-2 control-label\"></label>\r\n        <div class=\"col-md-10\">\r\n        " +
                    "    <input asp-for=\"ConfirmPassword\" class=\"form-control\" />\r\n            <span " +
                    "asp-validation-for=\"ConfirmPassword\" class=\"text-danger\"></span>\r\n        </div>" +
                    "\r\n    </div>\r\n    <div class=\"form-group\">\r\n        <div class=\"col-md-offset-2 " +
                    "col-md-10\">\r\n            <button type=\"submit\" class=\"btn btn-default\">Register<" +
                    "/button>\r\n        </div>\r\n    </div>\r\n</form>\r\n\r\n@section Scripts {\r\n    @{ awai" +
                    "t Html.RenderPartialAsync(\"_ValidationScriptsPartial\"); }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
