// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 15.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Mobioos.Generators.AspNetCore
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using Mobioos.Scaffold.TextTemplating;
    using Mobioos.Generators.AspNetCore;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\DEV\Generators\Mobioos\Common\Templates\Views\Account\SendCode.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class SendCode : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 1 "D:\DEV\Generators\Mobioos\Common\Templates\Views\Account\SendCode.tt"
 var model = (SmartAppInfo)Model; 
            
            #line default
            #line hidden
            this.Write("@model ");
            
            #line 2 "D:\DEV\Generators\Mobioos\Common\Templates\Views\Account\SendCode.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(@".Backend.Models.SendCodeViewModel
@{
    ViewData[""Title""] = ""Send Verification Code"";
}

<h2>@ViewData[""Title""].</h2>

<form asp-controller=""Account"" asp-action=""SendCode"" asp-route-returnurl=""@Model.ReturnUrl"" method=""post"" class=""form-horizontal"">
    <input asp-for=""RememberMe"" type=""hidden"" />
    <div class=""row"">
        <div class=""col-md-8"">
            Select Two-Factor Authentication Provider:
            <select asp-for=""SelectedProvider"" asp-items=""Model.Providers""></select>
            <button type=""submit"" class=""btn btn-default"">Submit</button>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync(""_ValidationScriptsPartial""); }
}
");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
