// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 16.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Mobioos.Generators.AspNetCore
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Common.Generator.Framework.Extensions;
    using Mobioos.Generators.AspNetCore;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Common\Templates\Views\Account\Register.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class Register : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 2 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Common\Templates\Views\Account\Register.tt"
 var model = (SmartAppInfo)Model; 
            
            #line default
            #line hidden
            this.Write("@model ");
            
            #line 3 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Common\Templates\Views\Account\Register.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(".Backend.Models.RegisterViewModel\r\n@{\r\n    ViewData[\"Title\"] = \"Register\";\r\n}\r\n\r\n" +
                    "<h2>@ViewData[\"Title\"].</h2>\r\n\r\n<form\r\n    asp-controller=\"GeneratorAccount\"\r\n  " +
                    "  asp-action=\"Register\"\r\n    asp-route-returnurl=\"@ViewData[\"ReturnUrl\"]\"\r\n    m" +
                    "ethod=\"post\"\r\n    class=\"form-horizontal\">\r\n    <h4>Create a new account.</h4>\r\n" +
                    "    <hr/>\r\n    <div\r\n        asp-validation-summary=\"All\"\r\n        class=\"text-d" +
                    "anger\"></div>\r\n    <div class=\"form-group\">\r\n        <label\r\n            asp-for" +
                    "=\"Email\"\r\n            class=\"col-md-2 control-label\"></label>\r\n        <div clas" +
                    "s=\"col-md-10\">\r\n            <input\r\n                asp-for=\"Email\"\r\n           " +
                    "     class=\"form-control\" />\r\n            <span\r\n                asp-validation-" +
                    "for=\"Email\"\r\n                class=\"text-danger\"></span>\r\n        </div>\r\n    </" +
                    "div>\r\n    <div class=\"form-group\">\r\n        <label\r\n            asp-for=\"Passwor" +
                    "d\"\r\n            class=\"col-md-2 control-label\"></label>\r\n        <div class=\"col" +
                    "-md-10\">\r\n            <input\r\n                asp-for=\"Password\"\r\n              " +
                    "  class=\"form-control\" />\r\n            <span\r\n                asp-validation-for" +
                    "=\"Password\"\r\n                class=\"text-danger\"></span>\r\n        </div>\r\n    </" +
                    "div>\r\n    <div class=\"form-group\">\r\n        <label\r\n            asp-for=\"Confirm" +
                    "Password\"\r\n            class=\"col-md-2 control-label\"></label>\r\n        <div cla" +
                    "ss=\"col-md-10\">\r\n            <input\r\n                asp-for=\"ConfirmPassword\"\r\n" +
                    "                class=\"form-control\" />\r\n            <span\r\n                asp-" +
                    "validation-for=\"ConfirmPassword\"\r\n                class=\"text-danger\"></span>\r\n " +
                    "       </div>\r\n    </div>\r\n    <div class=\"form-group\">\r\n        <div class=\"col" +
                    "-md-offset-2 col-md-10\">\r\n            <button\r\n                type=\"submit\"\r\n  " +
                    "              class=\"btn btn-default\">Register</button>\r\n        </div>\r\n    </d" +
                    "iv>\r\n</form>\r\n\r\n@section Scripts\r\n{\r\n    @{\r\n        await Html.RenderPartialAsy" +
                    "nc(\"_ValidationScriptsPartial\");\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
