// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 15.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Mobioos.Generators.AspNetCore
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using Mobioos.Scaffold.TextTemplating;
    using Mobioos.Generators.AspNetCore;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class EntityApiController : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 1 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
 var model = (EntityInfo)Model; var key = ((EntityInfo)Model).AllProperties() != null ? ((EntityInfo)Model).AllProperties().FirstOrDefault(p=>p.IsKey) : null; 
            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Linq;\r\nusing System.Net;\r\nusing System.Threading.Task" +
                    "s;\r\nusing Microsoft.AspNetCore.Authorization;\r\nusing Microsoft.AspNetCore.Mvc;\r\n" +
                    "using System.Collections.Generic;\r\nusing Microsoft.EntityFrameworkCore;\r\nusing ");
            
            #line 10 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write(".Backend.DataModels;\r\nusing ");
            
            #line 11 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write(".Backend.Models;\r\nusing ");
            
            #line 12 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write(".Backend.Services;\r\n\r\nnamespace ");
            
            #line 14 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write(".Backend.Api.");
            
            #line 14 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Version));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    [Route(\"api/");
            
            #line 16 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Version));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 16 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\")]\r\n\tpublic partial class ");
            
            #line 17 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("Controller\r\n        : Controller\r\n    {\r\n\t\tprivate I");
            
            #line 20 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("Service _");
            
            #line 20 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("Service;\r\n\r\n        public ");
            
            #line 22 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("Controller(I");
            
            #line 22 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("Service ");
            
            #line 22 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("Service)\r\n        {\r\n\t\t\t_");
            
            #line 24 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("Service = ");
            
            #line 24 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("Service;\r\n        }\r\n\r\n\t\t/// <summary>\r\n        /// Get all ");
            
            #line 28 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("s from database\r\n        /// </summary>\r\n        /// <returns></returns>\r\n\r\n     " +
                    "   /// <response code=\"200\">Ok</response>\r\n        // GET: api/");
            
            #line 33 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Version));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 33 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\r\n        [HttpGet(\"GetAll\")]\r\n        [ProducesResponseType(typeof(IEnumerable<");
            
            #line 35 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(">), 200)]\r\n        public async virtual Task<IActionResult> GetAll()\r\n        {\r\n" +
                    "\t\t\ttry\r\n            {\r\n                return Ok((_");
            
            #line 40 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("Service.GetAll()).AsQueryable());\r\n            }\r\n            catch (Exception xc" +
                    "p)\r\n            {\r\n                //log error\r\n                return Ok(Enumer" +
                    "able.Empty <");
            
            #line 45 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("> ().AsQueryable());\r\n            }\r\n        }\r\n");
            
            #line 48 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
if(key!=null){
            
            #line default
            #line hidden
            this.Write("\t\t/// <summary>\r\n        /// Get ");
            
            #line 50 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(" by id\r\n        /// </summary>\r\n        /// <param name=\"id\">");
            
            #line 52 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(" id</param>\r\n        /// <returns>Corresponding ");
            
            #line 53 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(" <see cref=\"");
            
            #line 53 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\" >");
            
            #line 53 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("</see></returns>\r\n        /// <response code=\"200\">Ok</response>\r\n        /// <re" +
                    "sponse code=\"404\">Not found</response>\r\n        [ProducesResponseType(typeof(");
            
            #line 56 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("), 200)]\r\n        // GET: api/");
            
            #line 57 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Version));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 57 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("/<id>\r\n\t\t[HttpGet(\"Get\")]\r\n        public async virtual Task<IActionResult> GetBy" +
                    "Id(");
            
            #line 59 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.CSharpType()));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n            try\r\n            {\r\n                var entity = awa" +
                    "it _");
            
            #line 63 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(@"Service.GetById(id);
                if (entity == null)
                {
                    return NotFound();
                }

                return Ok(entity);
            }
            catch (Exception xcp)
            {
                //log error
                return StatusCode((int)HttpStatusCode.InternalServerError);
            }
        }

		/// <summary>
        /// Update existing ");
            
            #line 79 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n        /// <param name=\"id\">");
            
            #line 81 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(" id</param>\r\n        /// <param name=\"entity\">");
            
            #line 82 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(@" to update</param>
        /// <response code=""204"">No content</response>
        /// <response code=""400"">Bad request</response>
        /// <response code=""404"">Not found</response>
        /// <response code=""500"">Internal error</response>
        // PUT: api/");
            
            #line 87 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Version));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 87 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("/<id>\r\n        [ProducesResponseType(typeof(void), 200)]\r\n\t\t[HttpPut(\"PutEntity\")" +
                    "]\r\n        public async virtual Task<IActionResult> PutEntity(");
            
            #line 90 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.CSharpType()));
            
            #line default
            #line hidden
            this.Write(" id, [FromBody] ");
            
            #line 90 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(" entity)\r\n        {\r\n            if (!ModelState.IsValid)\r\n            {\r\n       " +
                    "         return BadRequest(ModelState);\r\n            }\r\n\r\n\t\t\t");
            
            #line 97 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
 if (!string.IsNullOrEmpty(key.Id)) { 
            
            #line default
            #line hidden
            this.Write("            if (id != entity.");
            
            #line 98 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.Id));
            
            #line default
            #line hidden
            this.Write(")\r\n            {\r\n                return BadRequest();\r\n            }\r\n\t\t\t");
            
            #line 102 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 104 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
 if (!string.IsNullOrEmpty(key.Id)) { 
            
            #line default
            #line hidden
            this.Write("            // Gets the original entity from the database.\r\n            var origi" +
                    "nal = _");
            
            #line 106 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("Service.GetById(entity.");
            
            #line 106 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.Id));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t");
            
            #line 107 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"
            // If not found, return the 404 http status.
            if (original == null)
            {
                return NotFound();
            }

            // Sets a new rawVersion to the update entity.
            entity.RawVersion = System.BitConverter.GetBytes(DateTime.Now.Ticks);

            try
            {
                // Save changes to database.
                await _");
            
            #line 121 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(@"Service.Save(entity);

                // Return the 200 http status with no content.
                return  StatusCode((int)HttpStatusCode.OK);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!this.EntityExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            catch (Exception xcp)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError);
            }      
        }

		/// <summary>
        /// Create a new ");
            
            #line 144 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n        /// <param name=\"entity\">");
            
            #line 146 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(" to create</param>\r\n        /// <returns>New ");
            
            #line 147 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(" <see cref=\"");
            
            #line 147 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 147 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(@"</see></returns>
        /// <response code=""200"">Ok</response>
        /// <response code=""400"">Bad request</response>
        /// <response code=""409"">Conflict</response>
        /// <response code=""500"">Internal error</response>
        [ProducesResponseType(typeof(");
            
            #line 152 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("), 200)]\r\n        // POST: api/");
            
            #line 153 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Version));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 153 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t[HttpPost(\"PostEntity\")]\r\n        public async virtual Task<IActionResult> Po" +
                    "stEntity([FromBody] ");
            
            #line 155 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(" entity)\r\n        {\r\n            if (!ModelState.IsValid)\r\n            {\r\n       " +
                    "         return BadRequest(ModelState);\r\n            }            \r\n\r\n          " +
                    "  try\r\n            {\r\n                await _");
            
            #line 164 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("Service.Save(entity);\r\n                return this.Ok(entity);\r\n            }\r\n  " +
                    "          catch (DbUpdateException xcp)\r\n            {\r\n\t\t\t");
            
            #line 169 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
 if (!string.IsNullOrEmpty(key.Id)) { 
            
            #line default
            #line hidden
            this.Write("                if (this.EntityExists(entity.");
            
            #line 170 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.Id));
            
            #line default
            #line hidden
            this.Write("))\r\n                {\r\n                    return StatusCode((int)HttpStatusCode." +
                    "Conflict);\r\n                }\r\n                else\r\n                {\r\n        " +
                    "            throw xcp;\r\n                }\r\n\t\t\t\t");
            
            #line 178 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
}
            
            #line default
            #line hidden
            this.Write("            }\r\n            catch (Exception xcp) {\r\n                return Status" +
                    "Code((int)HttpStatusCode.InternalServerError);\r\n            }       \r\n        }\r" +
                    "\n\r\n\t\t/// <summary>\r\n        /// Delete an existing ");
            
            #line 186 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n        /// <param name=\"entity\">");
            
            #line 188 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(" to create</param>\r\n        /// <response code=\"200\">Ok</response>\r\n        /// <" +
                    "response code=\"404\">Not found</response>\r\n        /// <response code=\"500\">Inter" +
                    "nal error</response>\r\n        // DELETE: api/");
            
            #line 192 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Version));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 192 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("/<id>\r\n\t\t[HttpDelete(\"DeleteEntity\")]\r\n        public async virtual Task<IActionR" +
                    "esult> DeleteEntity(");
            
            #line 194 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.CSharpType()));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n            try\r\n            {\r\n                var entity = awa" +
                    "it _");
            
            #line 198 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("Service.GetById(id);\r\n                if (entity == null)\r\n                {\r\n   " +
                    "                 return NotFound();\r\n                }\r\n\r\n                await " +
                    "_");
            
            #line 204 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("Service.Delete(id);\r\n\r\n                return Ok(entity);\r\n            }\r\n       " +
                    "     catch (Exception xcp)\r\n            {\r\n                return StatusCode((in" +
                    "t)HttpStatusCode.InternalServerError);\r\n            }          \r\n        }\r\n\r\n\t\t" +
                    "");
            
            #line 214 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
 if (!string.IsNullOrEmpty(key.Id)) { 
            
            #line default
            #line hidden
            this.Write("        protected virtual bool EntityExists(");
            
            #line 215 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.CSharpType()));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n            return _");
            
            #line 217 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("Service.GetById(id) != null;\r\n        }\r\n\t\t");
            
            #line 219 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
}
            
            #line default
            #line hidden
            
            #line 220 "D:\DEV\Generators\Mobioos\Data\Templates\EntityApiController.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\tprotected override void Dispose(bool disposing)\r\n        {\r\n            if (d" +
                    "isposing)\r\n            {\r\n            }\r\n            base.Dispose(disposing);\r\n " +
                    "       }\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
