// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 16.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Mobioos.Generators.AspNetCore
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Common.Generator.Framework.Extensions;
    using Mobioos.Generators.AspNetCore;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\Views\CreateTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class CreateTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 2 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\Views\CreateTemplate.tt"
 var model = (EntityInfo)Model; 
            
            #line default
            #line hidden
            this.Write("@model ");
            
            #line 3 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\Views\CreateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write(".Backend.DataModels.");
            
            #line 3 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\Views\CreateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n@{\r\n    ViewBag.Title = \"Create\";\r\n    Layout = \"~/Views/Shared/_Layout.cshtm" +
                    "l\";\r\n}\r\n\r\n<h2>Create</h2>\r\n\r\n\r\n@using (Html.BeginForm()) \r\n{\r\n    @Html.AntiForg" +
                    "eryToken()\r\n    \r\n    <div class=\"form-horizontal\">\r\n        <h4>");
            
            #line 18 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\Views\CreateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("</h4>\r\n        <hr/>\r\n        @Html.ValidationSummary(\r\n            true,\r\n      " +
                    "      \"\",\r\n            new\r\n            {\r\n                @class=\"text-danger\"\r" +
                    "\n            })\r\n");
            
            #line 27 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\Views\CreateTemplate.tt"

        foreach (var property in model.GetProperties())
        {
            var propertyId = property.Id.ToPascalCase();

            
            #line default
            #line hidden
            this.Write("        <div class=\"form-group\">\r\n            @Html.LabelFor(m =>\r\n              " +
                    "  m.");
            
            #line 34 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\Views\CreateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyId));
            
            #line default
            #line hidden
            this.Write(",\r\n                htmlAttributes: new\r\n                {\r\n                    @c" +
                    "lass=\"control-label col-md-2\"\r\n                })\r\n            <div class=\"col-m" +
                    "d-10\">\r\n                @Html.EditorFor(m =>\r\n                    m.");
            
            #line 41 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\Views\CreateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyId));
            
            #line default
            #line hidden
            this.Write(@",
                    new
                    {
                        htmlAttributes = new
                        {
                            @class=""form-control""
                        }
                    })
                @Html.ValidationMessageFor(m =>
                    m.");
            
            #line 50 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\Views\CreateTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyId));
            
            #line default
            #line hidden
            this.Write(",\r\n                    \"\",\r\n                    new\r\n                    {\r\n     " +
                    "                   @class=\"text-danger\"\r\n                    })\r\n            </d" +
                    "iv>\r\n        </div>\r\n");
            
            #line 58 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\Views\CreateTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write(@"
        <div class=""form-group"">
            <div class=""col-md-offset-2 col-md-10"">
                <input
                    type=""submit""
                    value=""Create""
                    class=""btn btn-default"" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(
        ""Back to List"",
        ""Index"")
</div>

@section Scripts
{
    @Scripts.Render(""~/bundles/jqueryval"")
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
