// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 16.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Mobioos.Generators.AspNetCore
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Common.Generator.Framework.Extensions;
    using Mobioos.Generators.AspNetCore;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ApiConcernController : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 2 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

    var model = (LayoutInfo)Model;

    var actions = ((LayoutInfo)Model)
        .Actions
        .Where(a=> a.Type.ToString().IndexOf("data") == 0)
        .ToList();

    var key = ((EntityInfo)model.DataModel).GetProperties() != null ?
        ((EntityInfo)model.DataModel)
            .GetProperties()
            .FirstOrDefault(p => p.IsKey) :
        null;

    var lastType = ReferencedTypes.LastOrDefault();

    var keyProperty = model
        .DataModel
        .GetProperties()
        .FirstOrDefault(p => p.IsKey);

    var keyType = keyProperty != null ?
        keyProperty
            .ModelProperty?
            .Substring(
                0,
                keyProperty.ModelProperty.IndexOf(".")) :
        "";

    if (string.IsNullOrEmpty(keyType))
    {
        keyType = model
            .DataModel
            .GetEntityDirectReferences()
            .FirstOrDefault(p =>
                !p.IsAbstract)?
            .Id
            .CSharpType();
    }

    if (key == null)
    {
        key = model
            .DataModel
            .GetEntityDirectReferences()
            .FirstOrDefault()?
            .GetProperties()
            .FirstOrDefault(p => p.IsKey);
    }

            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Net;\r\nusing System.Linq;\r\nusing System.Threading.Task" +
                    "s;\r\nusing System.Collections.Generic;\r\nusing Microsoft.AspNetCore.Authorization;" +
                    "\r\nusing Microsoft.AspNetCore.Mvc;\r\nusing ");
            
            #line 59 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write(".Backend.DataModels;\r\nusing ");
            
            #line 60 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write(".Backend.Models;\r\nusing ");
            
            #line 61 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write(".Backend.Services;\r\nusing ");
            
            #line 62 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write(".Backend.ViewModels;\r\n\r\nnamespace ");
            
            #line 64 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write(".Backend.Api.");
            
            #line 64 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Concern.Id));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    /// <summary>\r\n    /// Controller responsible for all data interactions\r" +
                    "\n    /// with the ");
            
            #line 68 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(" view of the ");
            
            #line 68 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Concern.Id));
            
            #line default
            #line hidden
            this.Write(" Feature\r\n    /// </summary>\r\n    [Route(\"api/");
            
            #line 70 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Version));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 70 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            
            #line 70 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\")]\r\n    public partial class ");
            
            #line 71 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Concern.Id));
            
            #line default
            #line hidden
            
            #line 71 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("Controller : Controller\r\n    {\r\n");
            
            #line 73 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

    foreach (var type in ReferencedTypes)
    {

            
            #line default
            #line hidden
            this.Write("        private I");
            
            #line 77 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.Key));
            
            #line default
            #line hidden
            this.Write("Service _");
            
            #line 77 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.Key));
            
            #line default
            #line hidden
            this.Write("Service;\r\n");
            
            #line 78 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// Initialize a new instance of\r\n        /// <s" +
                    "ee cref = \"");
            
            #line 84 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write(".Backend.api.");
            
            #line 84 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Concern.Id));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 84 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Concern.Id));
            
            #line default
            #line hidden
            this.Write("\r\n        /// ");
            
            #line 85 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("Controller\"/> class.\r\n        /// </summary>\r\n        public ");
            
            #line 87 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Concern.Id));
            
            #line default
            #line hidden
            
            #line 87 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("Controller(\r\n");
            
            #line 88 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

    foreach (var type in ReferencedTypes)
    {

            
            #line default
            #line hidden
            this.Write("            I");
            
            #line 92 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.Key));
            
            #line default
            #line hidden
            this.Write("Service ");
            
            #line 92 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.Key));
            
            #line default
            #line hidden
            this.Write("Service");
            
            #line 92 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(!type.Equals(lastType) ? "," : ")"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 93 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

    }

            
            #line default
            #line hidden
            this.Write("        {\r\n");
            
            #line 97 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

    foreach (var type in ReferencedTypes)
    {

            
            #line default
            #line hidden
            this.Write("            _");
            
            #line 101 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.Key));
            
            #line default
            #line hidden
            this.Write("Service = ");
            
            #line 101 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.Key));
            
            #line default
            #line hidden
            this.Write("Service;\r\n");
            
            #line 102 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

    }

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n");
            
            #line 107 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

    if (model.DataModel != null
        && !string.IsNullOrEmpty(keyType))
    {
        if (!string.IsNullOrEmpty(keyType))
        {

            
            #line default
            #line hidden
            this.Write("        /// <summary>\r\n        /// Get all ");
            
            #line 115 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n        /// <returns><see cref = \"<%=List<");
            
            #line 117 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write(">%>\"/></returns>\r\n        /// <response code = \"200\">Ok</response>\r\n        // GE" +
                    "T: api/");
            
            #line 119 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Version));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 119 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write("\r\n        [HttpGet(\"GetAll\")]\r\n        [ProducesResponseType(\r\n            typeof" +
                    "(IEnumerable<");
            
            #line 122 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write(">),\r\n            200)]\r\n        public async virtual Task<IActionResult> GetAll()" +
                    "\r\n        {\r\n            try\r\n            {\r\n                var list = new List" +
                    "<");
            
            #line 128 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 129 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

            if (!string.IsNullOrEmpty(keyType))
            {

            
            #line default
            #line hidden
            this.Write("                var result = _");
            
            #line 133 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyType));
            
            #line default
            #line hidden
            this.Write("Service.GetAll();\r\n\r\n                if (result != null)\r\n                {\r\n    " +
                    "                foreach (var item in result)\r\n                    {\r\n           " +
                    "             list.Add(new ");
            
            #line 139 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write("().ConvertFromModel(\r\n");
            
            #line 140 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

                foreach (var referenceType in ReferencedTypes)
                {
                    if (referenceType.Key.Equals(keyType))
                    {

            
            #line default
            #line hidden
            this.Write("                            item");
            
            #line 146 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(!referenceType.Key.Equals(lastType.Key) ? "," : "));"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 147 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

                    }
                    else
                    {

            
            #line default
            #line hidden
            this.Write("                            new ");
            
            #line 152 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(referenceType.Key));
            
            #line default
            #line hidden
            this.Write("()");
            
            #line 152 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(!referenceType.Key.Equals(lastType.Key) ? "," : "));"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 153 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

                    }
                }

            
            #line default
            #line hidden
            this.Write("                }\r\n\r\n                    return this.Ok(await Task.FromResult(lis" +
                    "t));\r\n                }\r\n\r\n                return NotFound();\r\n");
            
            #line 163 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

            }
            else
            {

            
            #line default
            #line hidden
            this.Write("                return this.Ok(await Task.FromResult(list));\r\n");
            
            #line 169 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

            }

            
            #line default
            #line hidden
            this.Write("            }\r\n            catch (Exception xcp)\r\n            {\r\n                " +
                    "//log error\r\n                return Ok(Enumerable.Empty<");
            
            #line 176 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("ViewModel>().AsQueryable());\r\n            }\r\n        }\r\n\r\n        /// <summary>\r\n" +
                    "        /// ");
            
            #line 181 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Description ?? model.DataModel.Description));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n        /// <param name = \"date\">The date to use to ret" +
                    "reive the\r\n        /// <see cref = \"");
            
            #line 184 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write("\"/> collection from</param>\r\n        /// <returns><see cref = \"<%=");
            
            #line 185 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write(@"%>""/></returns>
        /// <response code = ""200"">Ok</response>
        /// <response code = ""304"">NotModified</response>
        /// <response code = ""404"">Not found</response>
        /// <response code = ""500"">Internal error</response>
        [HttpGet(""Get"")]
        [ProducesResponseType(
            typeof(");
            
            #line 192 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write("),\r\n            200)]\r\n        public async Task<IActionResult> Get(");
            
            #line 194 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key != null ? key.CSharpType() : "int"));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n            try\r\n            {\r\n");
            
            #line 198 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

            if (!string.IsNullOrEmpty(keyType))
            {

            
            #line default
            #line hidden
            this.Write("                var entity = await _");
            
            #line 202 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyType));
            
            #line default
            #line hidden
            this.Write("Service.GetById(id);\r\n\r\n                if (entity != null)\r\n                {\r\n " +
                    "                   return this.Ok(await Task.FromResult(new ");
            
            #line 206 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write("().ConvertFromModel(\r\n");
            
            #line 207 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

                foreach (var referenceType in ReferencedTypes)
                {
                    if (referenceType.Key.Equals(keyType))
                    {

            
            #line default
            #line hidden
            this.Write("                        entity");
            
            #line 213 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(!referenceType.Key.Equals(lastType.Key) ? "," : ")));"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 214 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

                    }
                    else
                    {

            
            #line default
            #line hidden
            this.Write("                        new ");
            
            #line 219 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(referenceType.Key));
            
            #line default
            #line hidden
            this.Write("()");
            
            #line 219 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(!referenceType.Key.Equals(lastType.Key) ? "," : ")));"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 220 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

                    }
                }

            
            #line default
            #line hidden
            this.Write("                }\r\n\r\n                return NotFound();\r\n");
            
            #line 227 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

            }
            else
            {

            
            #line default
            #line hidden
            this.Write("                return this.Ok(await Task.FromResult(new ");
            
            #line 232 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write("()));\r\n");
            
            #line 233 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

            }

            
            #line default
            #line hidden
            this.Write("            }\r\n            catch (Exception xcp)\r\n            {\r\n                " +
                    "return new StatusCodeResult((int)HttpStatusCode.InternalServerError);\r\n         " +
                    "   }\r\n        }\r\n\r\n        /// <summary>\r\n        /// Update existing ");
            
            #line 244 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n        /// <param name = \"id\">");
            
            #line 246 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write(" id</param>\r\n        /// <param name = \"entity\">");
            
            #line 247 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write(@" to update</param>
        /// <response code = ""204"">No content</response>
        /// <response code = ""400"">Bad request</response>
        /// <response code = ""404"">Not found</response>
        /// <response code = ""500"">Internal error</response>
        // PUT: api/");
            
            #line 252 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Version));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 252 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write("/<id>\r\n        [ProducesResponseType(\r\n            typeof(void),\r\n            200" +
                    ")]\r\n        [HttpPut(\"PutEntity\")]\r\n        public async virtual Task<IActionRes" +
                    "ult> PutEntity(\r\n            ");
            
            #line 258 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key != null ? key.CSharpType() : "int"));
            
            #line default
            #line hidden
            this.Write(" id,\r\n            [FromBody] ");
            
            #line 259 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write(" model)\r\n        {\r\n            if (!ModelState.IsValid)\r\n            {\r\n        " +
                    "        return BadRequest(ModelState);\r\n            }\r\n\r\n");
            
            #line 266 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

            if (key != null
                && !string.IsNullOrEmpty(key.Id))
            {

                if (model
                    .DataModel
                    .GetProperties()
                    .FirstOrDefault(p => p.IsKey) != null)
                {

            
            #line default
            #line hidden
            this.Write("            if (id != model.");
            
            #line 277 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.Id));
            
            #line default
            #line hidden
            this.Write(")\r\n            {\r\n                return BadRequest();\r\n            }\r\n");
            
            #line 281 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

                }
                else
                {

            
            #line default
            #line hidden
            this.Write("            if (id != model.");
            
            #line 286 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.GetEntityDirectReferences().FirstOrDefault()?.Id));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 286 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.Id));
            
            #line default
            #line hidden
            this.Write(")\r\n            {\r\n                return BadRequest();\r\n            }\r\n");
            
            #line 290 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

                }
            }

            if (key != null
                && !string.IsNullOrEmpty(key.Id))
            {

            
            #line default
            #line hidden
            this.Write("            // Gets the original entity from the database.\r\n            var origi" +
                    "nal = _");
            
            #line 299 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyType));
            
            #line default
            #line hidden
            this.Write("Service.GetById(id);\r\n");
            
            #line 300 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

            }

            
            #line default
            #line hidden
            this.Write("\r\n            // If not found, return the 404 http status.\r\n            if (origi" +
                    "nal == null)\r\n            {\r\n                return NotFound();\r\n            }\r\n" +
                    "           \r\n            try\r\n            {\r\n");
            
            #line 312 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

            if (model
                .DataModel
                .GetProperties()
                .FirstOrDefault() != null)
            {

            
            #line default
            #line hidden
            this.Write("                var entity = model.ConvertToModel();\r\n");
            
            #line 320 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

            }
            else if (model
                .DataModel
                .GetEntityDirectReferences()
                .FirstOrDefault() != null)
            {

            
            #line default
            #line hidden
            this.Write("                var entity = model.");
            
            #line 328 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyType));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 329 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

            }

            
            #line default
            #line hidden
            this.Write("                // Sets a new rawVersion to the update entity.\r\n                e" +
                    "ntity.RawVersion = System\r\n                    .BitConverter\r\n                  " +
                    "  .GetBytes(DateTime.Now.Ticks);\r\n\r\n");
            
            #line 337 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

            if (!string.IsNullOrEmpty(keyType))
            {

            
            #line default
            #line hidden
            this.Write("                // Save changes to database.\r\n                await _");
            
            #line 342 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyType));
            
            #line default
            #line hidden
            this.Write("Service.Save(entity);\r\n\r\n");
            
            #line 344 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

            }

            
            #line default
            #line hidden
            this.Write(@"
                // Return the 200 http status with no content.
                return  StatusCode((int)HttpStatusCode.OK);
            }
            catch (Exception xcp)
            {
                return StatusCode((int)HttpStatusCode.InternalServerError);
            }
        }

        /// <summary>
        /// Create a new ");
            
            #line 358 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n        /// <param name = \"entity\">");
            
            #line 360 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write(" to create</param>\r\n        /// <returns>New ");
            
            #line 361 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(" <see cref = \"");
            
            #line 361 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 361 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write(@"</see></returns>
        /// <response code = ""200"">Ok</response>
        /// <response code = ""400"">Bad request</response>
        /// <response code = ""409"">Conflict</response>
        /// <response code = ""500"">Internal error</response>
        [ProducesResponseType(
            typeof(");
            
            #line 367 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write("),\r\n            200)]\r\n        // POST: api/");
            
            #line 369 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Version));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 369 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write("\r\n        [HttpPost(\"PostEntity\")]\r\n        public async virtual Task<IActionResu" +
                    "lt> PostEntity(\r\n            [FromBody] ");
            
            #line 372 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write(" model)\r\n        {\r\n            if (!ModelState.IsValid)\r\n            {\r\n        " +
                    "        return BadRequest(ModelState);\r\n            }\r\n\r\n            try\r\n      " +
                    "      {\r\n");
            
            #line 381 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

            if (model
                .DataModel
                .GetProperties()
                .FirstOrDefault() != null)
            {

            
            #line default
            #line hidden
            this.Write("                var entity = model.ConvertToModel();\r\n");
            
            #line 389 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

            }
            else if (model
                .DataModel
                .GetEntityDirectReferences()
                .FirstOrDefault() != null)
            {

            
            #line default
            #line hidden
            this.Write("                var entity = model.");
            
            #line 397 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyType));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 398 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

            }

            if (!string.IsNullOrEmpty(keyType))
            {

            
            #line default
            #line hidden
            this.Write("                await _");
            
            #line 404 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyType));
            
            #line default
            #line hidden
            this.Write("Service.Save(entity);\r\n");
            
            #line 405 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

            }

            
            #line default
            #line hidden
            this.Write("                return this.Ok(entity);\r\n            }\r\n            catch (Except" +
                    "ion xcp) {\r\n                return StatusCode((int)HttpStatusCode.InternalServer" +
                    "Error);\r\n            }\r\n        }\r\n\r\n");
            
            #line 415 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

        }

            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// Delete an existing ");
            
            #line 420 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n        /// <param name = \"entity\">");
            
            #line 422 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(" to create</param>\r\n        /// <response code = \"200\">Ok</response>\r\n        ///" +
                    " <response code = \"404\">Not found</response>\r\n        /// <response code = \"500\"" +
                    ">Internal error</response>\r\n        // DELETE: api/");
            
            #line 426 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Version));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 426 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("/<id>\r\n        [HttpDelete(\"DeleteEntity\")]\r\n        public async virtual Task<IA" +
                    "ctionResult> DeleteEntity(\r\n            ");
            
            #line 429 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key != null ? key.CSharpType() : "int"));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n            try\r\n            {\r\n");
            
            #line 433 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

        if (!string.IsNullOrEmpty(keyType))
        {

            
            #line default
            #line hidden
            this.Write("                var entity = await _");
            
            #line 437 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyType));
            
            #line default
            #line hidden
            this.Write("Service.GetById(id);\r\n\r\n                if (entity == null)\r\n                {\r\n " +
                    "                   return NotFound();\r\n                }\r\n\r\n                awai" +
                    "t _");
            
            #line 444 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyType));
            
            #line default
            #line hidden
            this.Write("Service.Delete(id);\r\n\r\n                return Ok(entity);\r\n");
            
            #line 447 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

        }
        else
        {

            
            #line default
            #line hidden
            this.Write("\r\n                return Ok(new ");
            
            #line 453 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.DataModel.Id));
            
            #line default
            #line hidden
            this.Write("());\r\n");
            
            #line 454 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

        }

            
            #line default
            #line hidden
            this.Write("            }\r\n            catch (Exception xcp)\r\n            {\r\n                " +
                    "return StatusCode((int)HttpStatusCode.InternalServerError);\r\n            }\r\n    " +
                    "    }\r\n\r\n");
            
            #line 464 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\ApiConcernController.tt"

    }

            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
