// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 16.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Mobioos.Generators.AspNetCore
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Common.Generator.Framework.Extensions;
    using Mobioos.Generators.AspNetCore;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\DbContext.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DbContext : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 2 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\DbContext.tt"

    var model = (SmartAppInfo)Model;
    var models = model.GetModels();

            
            #line default
            #line hidden
            this.Write("using Microsoft.EntityFrameworkCore;\r\nusing Microsoft.AspNetCore.Identity.EntityF" +
                    "rameworkCore;\r\nusing Microsoft.AspNetCore.Identity;\r\nusing ");
            
            #line 9 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\DbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(".Backend.DataModels;\r\n\r\nnamespace ");
            
            #line 11 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\DbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(@".Backend.Models
{
    public partial class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder
                .Entity<IdentityUserLogin<string>>()
                .HasKey(e => new
                {
                    e.UserId
                });

            builder
                .Entity<IdentityRole>()
                .HasKey(e => new
                {
                    e.Id
                });

            builder
                .Entity<IdentityUserRole<string>>()
                .HasKey(e => new
                {
                    e.RoleId,
                    e.UserId
                });

            builder
                .Entity<IdentityUserToken<string>>()
                .HasKey(e => new
                {
                    e.UserId
                });

");
            
            #line 51 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\DbContext.tt"

    if (models != null)
    {
        foreach (var entity in models)
        {
            var primaryKey = entity
                .GetProperties()?
                .FirstOrDefault(p => p.IsKey);

            if (!entity.IsAbstract
                && !entity.IsEnum
                && !entity.IsInherited(models)
                && primaryKey != null)
            {
                var lastKey = entity
                    .GetProperties()
                    .Where(p => p.IsKey)
                    .LastOrDefault();

            
            #line default
            #line hidden
            this.Write("            builder\r\n                .Entity<");
            
            #line 71 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\DbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Id));
            
            #line default
            #line hidden
            this.Write(">()\r\n                .HasKey(e => new\r\n                {\r\n");
            
            #line 74 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\DbContext.tt"

                foreach (var key in entity
                    .GetProperties()
                    .Where(p => p.IsKey))
                {

            
            #line default
            #line hidden
            this.Write("                    e.");
            
            #line 80 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\DbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.Id.ToPascalCase()));
            
            #line default
            #line hidden
            
            #line 80 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\DbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(!key.Equals(lastKey) ? " ," : ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 81 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\DbContext.tt"

                }

            
            #line default
            #line hidden
            this.Write("                });\r\n");
            
            #line 85 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\DbContext.tt"

            }
        }
    }

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        protected override void OnConfiguring(DbContextOptionsBuilde" +
                    "r optionsBuilder)\r\n        {\r\n            base.OnConfiguring(optionsBuilder);\r\n " +
                    "       }\r\n\r\n");
            
            #line 97 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\DbContext.tt"

    if (models != null)
    {
        foreach (var entity in models)
        {
            var key = entity
                .GetProperties()?
                .FirstOrDefault(p => p.IsKey);

            if (!entity.IsAbstract
                && !entity.IsEnum
                && !entity.IsInherited(models)
                && key != null)
            {

            
            #line default
            #line hidden
            this.Write("\r\n        public DbSet<");
            
            #line 113 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\DbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Id));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 113 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\DbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Id));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 114 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Data\Templates\DbContext.tt"

            }
        }
    }

            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
