// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 15.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Mobioos.Generators.AspNetCore
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Generators.AspNetCore;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Common\Templates\Views\Shared\LayoutTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class LayoutTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 1 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Common\Templates\Views\Shared\LayoutTemplate.tt"
 var model = (SmartAppInfo)Model; 
            
            #line default
            #line hidden
            this.Write(@"@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset=""utf-8"" />
    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"" />
    <title>@ViewData[""Title""] - ");
            
            #line 8 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Common\Templates\Views\Shared\LayoutTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Title));
            
            #line default
            #line hidden
            this.Write("</title>\r\n\r\n    <environment names=\"Development\">\r\n        <link rel=\"stylesheet\"" +
                    " href=\"~/lib/bootstrap/dist/css/bootstrap.css\" />\r\n        <link rel=\"stylesheet" +
                    "\" href=\"~/css/site.css\" />\r\n    </environment>\r\n    <environment names=\"Staging," +
                    "Production\">\r\n        <link rel=\"stylesheet\" href=\"https://ajax.aspnetcdn.com/aj" +
                    "ax/bootstrap/3.3.7/css/bootstrap.min.css\"\r\n              asp-fallback-href=\"~/li" +
                    "b/bootstrap/dist/css/bootstrap.min.css\"\r\n              asp-fallback-test-class=\"" +
                    "sr-only\" asp-fallback-test-property=\"position\" asp-fallback-test-value=\"absolute" +
                    "\" />\r\n        <link rel=\"stylesheet\" href=\"~/css/site.min.css\" asp-append-versio" +
                    "n=\"true\" />\r\n    </environment>\r\n    @Html.Raw(JavaScriptSnippet.FullScript)\r\n</" +
                    "head>\r\n<body>\r\n    <nav class=\"navbar navbar-inverse navbar-fixed-top\">\r\n       " +
                    " <div class=\"container\">\r\n            <div class=\"navbar-header\">\r\n             " +
                    "   <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-targe" +
                    "t=\".navbar-collapse\">\r\n                    <span class=\"sr-only\">Toggle navigati" +
                    "on</span>\r\n                    <span class=\"icon-bar\"></span>\r\n                 " +
                    "   <span class=\"icon-bar\"></span>\r\n                    <span class=\"icon-bar\"></" +
                    "span>\r\n                </button>\r\n                <a asp-area=\"\" asp-controller=" +
                    "\"Home\" asp-action=\"Index\" class=\"navbar-brand\">AspNetCore</a>\r\n            </div" +
                    ">\r\n            <div class=\"navbar-collapse collapse\">\r\n                <ul class" +
                    "=\"nav navbar-nav\">\r\n                    <li><a asp-area=\"\" asp-controller=\"Home\"" +
                    " asp-action=\"Index\">Home</a></li>\r\n                    <li><a asp-area=\"\" asp-co" +
                    "ntroller=\"Home\" asp-action=\"About\">About</a></li>\r\n                    <li><a as" +
                    "p-area=\"\" asp-controller=\"Home\" asp-action=\"Contact\">Contact</a></li>\r\n         " +
                    "       </ul>\r\n                @await Html.PartialAsync(\"_LoginPartial\")\r\n       " +
                    "     </div>\r\n        </div>\r\n    </nav>\r\n    <div class=\"container body-content\"" +
                    ">\r\n        @RenderBody()\r\n        <hr />\r\n        <footer>\r\n            <p>&copy" +
                    "; 2017 - AspNetCore</p>\r\n        </footer>\r\n    </div>\r\n\r\n    <environment names" +
                    "=\"Development\">\r\n        <script src=\"~/lib/jquery/dist/jquery.js\"></script>\r\n  " +
                    "      <script src=\"~/lib/bootstrap/dist/js/bootstrap.js\"></script>\r\n        <scr" +
                    "ipt src=\"~/js/site.js\" asp-append-version=\"true\"></script>\r\n    </environment>\r\n" +
                    "    <environment names=\"Staging,Production\">\r\n        <script src=\"https://ajax." +
                    "aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js\"\r\n                asp-fallback-src" +
                    "=\"~/lib/jquery/dist/jquery.min.js\"\r\n                asp-fallback-test=\"window.jQ" +
                    "uery\"\r\n                crossorigin=\"anonymous\"\r\n                integrity=\"sha38" +
                    "4-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk\">\r\n        </" +
                    "script>\r\n        <script src=\"https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bo" +
                    "otstrap.min.js\"\r\n                asp-fallback-src=\"~/lib/bootstrap/dist/js/boots" +
                    "trap.min.js\"\r\n                asp-fallback-test=\"window.jQuery && window.jQuery." +
                    "fn && window.jQuery.fn.modal\"\r\n                crossorigin=\"anonymous\"\r\n        " +
                    "        integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8w" +
                    "GNIcPD7Txa\">\r\n        </script>\r\n        <script src=\"~/js/site.min.js\" asp-appe" +
                    "nd-version=\"true\"></script>\r\n    </environment>\r\n\r\n    @RenderSection(\"Scripts\"," +
                    " required: false)\r\n</body>\r\n</html>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
