// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 16.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Mobioos.Generators.AspNetCore
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Common.Generator.Framework.Extensions;
    using Mobioos.Generators.AspNetCore;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Security\Templates\FacebookApiResponses.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class FacebookApiResponses : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 2 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Security\Templates\FacebookApiResponses.tt"
 var model = (SmartAppInfo)Model; 
            
            #line default
            #line hidden
            this.Write("using Newtonsoft.Json;\r\n\r\nnamespace ");
            
            #line 5 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Mobioos.Generators.AspNetCore\Security\Templates\FacebookApiResponses.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(".Backend.Auth\r\n{\r\n    internal class FacebookUserData\r\n    {\r\n        public long" +
                    " Id { get; set; }\r\n        public string Email { get; set; }\r\n        public str" +
                    "ing Name { get; set; }\r\n\r\n        [JsonProperty(\"first_name\")]\r\n        public s" +
                    "tring FirstName { get; set; }\r\n\r\n        [JsonProperty(\"last_name\")]\r\n        pu" +
                    "blic string LastName { get; set; }\r\n\r\n        public string Gender { get; set; }" +
                    "\r\n        public string Locale { get; set; }\r\n        public FacebookPictureData" +
                    " Picture { get; set; }\r\n    }\r\n\r\n    internal class FacebookPictureData\r\n    {\r\n" +
                    "        public FacebookPicture Data { get; set; }\r\n    }\r\n\r\n    internal class F" +
                    "acebookPicture\r\n    {\r\n        public int Height { get; set; }\r\n        public i" +
                    "nt Width { get; set; }\r\n\r\n        [JsonProperty(\"is_silhouette\")]\r\n        publi" +
                    "c bool IsSilhouette { get; set; }\r\n\r\n        public string Url { get; set; }\r\n  " +
                    "  }\r\n\r\n    internal class FacebookUserAccessTokenData\r\n    {\r\n        [JsonPrope" +
                    "rty(\"app_id\")]\r\n        public long AppId { get; set; }\r\n\r\n        public string" +
                    " Type { get; set; }\r\n        public string Application { get; set; }\r\n\r\n        " +
                    "[JsonProperty(\"expires_at\")]\r\n        public long ExpiresAt { get; set; }\r\n\r\n   " +
                    "     [JsonProperty(\"is_valid\")]\r\n        public bool IsValid { get; set; }\r\n\r\n  " +
                    "      [JsonProperty(\"user_id\")]\r\n        public long UserId { get; set; }\r\n    }" +
                    "\r\n\r\n    internal class FacebookUserAccessTokenValidation\r\n    {\r\n        public " +
                    "FacebookUserAccessTokenData Data { get; set; }\r\n    }\r\n\r\n    internal class Face" +
                    "bookAppAccessToken\r\n    {\r\n        [JsonProperty(\"token_type\")]\r\n        public " +
                    "string TokenType { get; set; }\r\n\r\n        [JsonProperty(\"access_token\")]\r\n      " +
                    "  public string AccessToken { get; set; }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
