// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 15.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Mobioos.Generators.AspNetCore
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Generators.AspNetCore;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ApiPostTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 1 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
 var action = (ApiActionInfo)Model; 
            
            #line default
            #line hidden
            
            #line 2 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
 var firstParameter = action.Parameters.AsEnumerable().FirstOrDefault(); 
            
            #line default
            #line hidden
            this.Write("\t\t\tif (!ModelState.IsValid)\r\n\t\t\t{\r\n\t\t\t\treturn BadRequest(ModelState);\r\n\t\t\t}\r\n\r\n\t\t" +
                    "\ttry\r\n\t\t\t{\r\n");
            
            #line 10 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
 if(firstParameter.DataModel?.PropertyTypes() != null) {
            
            #line default
            #line hidden
            
            #line 11 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
 foreach(var entity in firstParameter.DataModel.PropertyTypes()) { 
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
 if (firstParameter != null && !string.IsNullOrEmpty(firstParameter.Id)) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\tvar ");
            
            #line 13 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Key));
            
            #line default
            #line hidden
            this.Write(" =  ");
            
            #line 13 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(firstParameter.Id));
            
            #line default
            #line hidden
            this.Write(".Get");
            
            #line 13 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Key));
            
            #line default
            #line hidden
            this.Write("FromViewModel();\r\n\t\t\t\tawait _");
            
            #line 14 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Key));
            
            #line default
            #line hidden
            this.Write("Service.Save(");
            
            #line 14 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Key));
            
            #line default
            #line hidden
            this.Write(" );\r\n");
            
            #line 15 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
}}
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
 if(firstParameter.DataModel?.ReferencedTypes() != null) {
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
 foreach(var entity in firstParameter.DataModel.ReferencedTypes()) { 
            
            #line default
            #line hidden
            
            #line 19 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
 if (firstParameter != null && !string.IsNullOrEmpty(firstParameter.Id) && !firstParameter.DataModel.PropertyTypes().Keys.Contains(entity.Key)) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\tvar ");
            
            #line 20 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Key));
            
            #line default
            #line hidden
            this.Write("  =  ");
            
            #line 20 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(firstParameter.Id));
            
            #line default
            #line hidden
            this.Write(".Get");
            
            #line 20 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Key));
            
            #line default
            #line hidden
            this.Write("FromViewModel();\r\n\t\t\t\tawait _");
            
            #line 21 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Key));
            
            #line default
            #line hidden
            this.Write("Service.Save(");
            
            #line 21 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Key));
            
            #line default
            #line hidden
            this.Write(" );\r\n");
            
            #line 22 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
}}
            
            #line default
            #line hidden
            
            #line 23 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Api\Templates\Api\ApiPostTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\treturn this.Ok(true);\r\n\t\t\t}\r\n\t\t\tcatch (Exception xcp) {\r\n\t\t\t\t//log exceptio" +
                    "n\r\n\t\t\t\treturn StatusCode((int)HttpStatusCode.InternalServerError);\r\n\t\t\t}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
