// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 15.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Mobioos.Generators.AspNetCore
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Generators.AspNetCore;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Common\Templates\AppSettingsTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class AppSettingsTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 1 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Common\Templates\AppSettingsTemplate.tt"
 var model = (SmartAppInfo)Model; 
            
            #line default
            #line hidden
            this.Write(@"{
  ""ConnectionStrings"": {
    ""DefaultConnection"": ""Server=(localdb)\\mssqllocaldb;Database=aspnet-AspNetCore-29838208-6d0d-47f0-babd-96e19f25cb8c;Trusted_Connection=True;MultipleActiveResultSets=true""
  },
  ""Logging"": {
    ""IncludeScopes"": false,
    ""LogLevel"": {
      ""Default"": ""Warning""
    }
  },
  ""JwtIssuerOptions"": {
    ""Issuer"": ""webApi"",
    ""Audience"": ""http://localhost:5000/""
  }");
            
            #line 15 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Common\Templates\AppSettingsTemplate.tt"
 if(AuthenticationKeys.Keys.Contains("FacebookAuthConsumerKey") && AuthenticationKeys.Keys.Contains("FacebookAuthConsumerSecret")) {
            
            #line default
            #line hidden
            this.Write(",\r\n  \"AuthSettings\": {\r\n    \"FacebookAppId\": \"");
            
            #line 17 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Common\Templates\AppSettingsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AuthenticationKeys["FacebookAuthConsumerKey"]));
            
            #line default
            #line hidden
            this.Write("\",\r\n    \"FacebookAppSecret\": \"");
            
            #line 18 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Common\Templates\AppSettingsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AuthenticationKeys["FacebookAuthConsumerSecret"]));
            
            #line default
            #line hidden
            this.Write("\"\r\n  }\r\n");
            
            #line 20 "C:\Users\PC\Documents\Gits\ASP.NET-Core-MVC\src\Common\Templates\AppSettingsTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
