// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 15.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Mobioos.Generators.AspNetCore
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using Mobioos.Scaffold.TextTemplating;
    using Mobioos.Generators.AspNetCore;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\DEV\Generators\Mobioos\Common\Templates\Project.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class Project : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 1 "D:\DEV\Generators\Mobioos\Common\Templates\Project.tt"
 var model = (SmartAppInfo)Model; 
            
            #line default
            #line hidden
            this.Write("  <Project Sdk=\"Microsoft.NET.Sdk.Web\">\r\n    <PropertyGroup>\r\n      <TargetFramew" +
                    "ork>netcoreapp2.0</TargetFramework>\r\n      <PreserveCompilationContext>true</Pre" +
                    "serveCompilationContext>\r\n      <AssemblyName>");
            
            #line 6 "D:\DEV\Generators\Mobioos\Common\Templates\Project.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(".Backend</AssemblyName>\r\n      <OutputType>Exe</OutputType>\r\n      <PackageId>");
            
            #line 8 "D:\DEV\Generators\Mobioos\Common\Templates\Project.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write("</PackageId>\r\n      <UserSecretsId>aspnet-");
            
            #line 9 "D:\DEV\Generators\Mobioos\Common\Templates\Project.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(UserSecret));
            
            #line default
            #line hidden
            this.Write("</UserSecretsId>\r\n      <AssetTargetFallback>$(AssetTargetFallback);portable-net4" +
                    "5+win8+wp8+wpa81;</AssetTargetFallback>\r\n      <RootNamespace>");
            
            #line 11 "D:\DEV\Generators\Mobioos\Common\Templates\Project.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id));
            
            #line default
            #line hidden
            this.Write(".Backend</RootNamespace>\r\n    </PropertyGroup>\r\n    <ItemGroup>\r\n      <PackageRe" +
                    "ference Include=\"Microsoft.ApplicationInsights.AspNetCore\" Version=\"2.0.0\" />\r\n " +
                    "     <PackageReference Include=\"Microsoft.AspNetCore\" Version=\"2.0.1\" />\r\n      " +
                    "<PackageReference Include=\"Microsoft.AspNetCore.Authentication.Cookies\" Version=" +
                    "\"2.0.1\" />\r\n      <PackageReference Include=\"Microsoft.AspNetCore\" Version=\"2.0." +
                    "1\" />\r\n      <PackageReference Include=\"Microsoft.AspNetCore.Authentication.Abst" +
                    "ractions\" Version=\"2.0.1\" />\r\n      <PackageReference Include=\"Microsoft.AspNetC" +
                    "ore.Authentication.Cookies\" Version=\"2.0.1\" />\r\n      <PackageReference Include=" +
                    "\"Microsoft.AspNetCore.Authentication.Core\" Version=\"2.0.1\" />\r\n      <PackageRef" +
                    "erence Include=\"Microsoft.AspNetCore.Authentication.Facebook\" Version=\"2.0.1\" />" +
                    "\r\n      <PackageReference Include=\"Microsoft.AspNetCore.Authentication.Google\" V" +
                    "ersion=\"2.0.1\" />\r\n      <PackageReference Include=\"Microsoft.AspNetCore.Authent" +
                    "ication.JwtBearer\" Version=\"2.0.1\" />\r\n      <PackageReference Include=\"Microsof" +
                    "t.AspNetCore.Authentication.MicrosoftAccount\" Version=\"2.0.1\" />\r\n      <Package" +
                    "Reference Include=\"Microsoft.AspNetCore.Authentication.Twitter\" Version=\"2.0.1\" " +
                    "/>\r\n      <PackageReference Include=\"Microsoft.AspNetCore.Diagnostics.EntityFram" +
                    "eworkCore\" Version=\"2.0.1\" />\r\n      <PackageReference Include=\"Microsoft.AspNet" +
                    "Core.Identity.EntityFrameworkCore\" Version=\"2.0.1\" />\r\n      <PackageReference I" +
                    "nclude=\"Microsoft.AspNetCore.Mvc\" Version=\"2.0.2\" />\r\n      <PackageReference In" +
                    "clude=\"Microsoft.AspNetCore.StaticFiles\" Version=\"2.0.1\" />\r\n      <PackageRefer" +
                    "ence Include=\"Microsoft.EntityFrameworkCore.Design\" Version=\"2.0.1\" PrivateAsset" +
                    "s=\"All\" />\r\n      <PackageReference Include=\"Microsoft.EntityFrameworkCore.SqlSe" +
                    "rver\" Version=\"2.0.1\" />\r\n      <PackageReference Include=\"Microsoft.EntityFrame" +
                    "workCore.SqlServer.Design\" Version=\"1.1.5\" PrivateAssets=\"All\" />\r\n      <Packag" +
                    "eReference Include=\"Microsoft.EntityFrameworkCore.Tools\" Version=\"2.0.1\" Private" +
                    "Assets=\"All\" />\r\n      <PackageReference Include=\"Microsoft.Extensions.Configura" +
                    "tion.UserSecrets\" Version=\"2.0.0\" />\r\n      <PackageReference Include=\"Microsoft" +
                    ".Extensions.Logging.Debug\" Version=\"2.0.0\" />\r\n      <PackageReference Include=\"" +
                    "Microsoft.VisualStudio.Web.CodeGeneration.Design\" Version=\"2.0.2\" PrivateAssets=" +
                    "\"All\" />\r\n      <PackageReference Include=\"Microsoft.VisualStudio.Web.BrowserLin" +
                    "k\" Version=\"2.0.1\" />\r\n      <PackageReference Include=\"Swashbuckle.AspNetCore\" " +
                    "Version=\"1.1.0\" />\r\n    </ItemGroup>\r\n    <ItemGroup>\r\n      <DotNetCliToolRefer" +
                    "ence Include=\"Microsoft.EntityFrameworkCore.Tools.DotNet\" Version=\"2.0.1\" />\r\n  " +
                    "    <DotNetCliToolReference Include=\"Microsoft.Extensions.SecretManager.Tools\" V" +
                    "ersion=\"2.0.0\" />\r\n      <DotNetCliToolReference Include=\"Microsoft.VisualStudio" +
                    ".Web.CodeGeneration.Tools\" Version=\"2.0.2\" />\r\n    </ItemGroup>\r\n\r\n  </Project>\r" +
                    "\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
